# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wig Solutions | Teconologia 
email: iagovelasco@hotmail.com
description: > 
  Uma empresa que oferece serviço para condominios, empresas e dos mais
  diversos portes e segmentos. Equipe preparada para deixar nossos cientes satisfeitos. 
  Trabalhamos somente com equipamentos novos, 
  sendo todos das mais renomadas marcas existentes no mercado nacional e internacional.
#
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
